sen301/foodNet/urls.py
from django.urls import path

from . import views

app_name = "foodNet"
urlpatterns = [
    # path("", views.test, name="test"),
    path("home", views.home_page, name="home_page"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("market/", views.market, name="market"),
    path("market/cart/", views.cart, name="cart"),
    path("market/cart/checkout/", views.checkout, name="checkout"),
    path("market/product/<int:product_id>", views.view_product, name="view_product"),
    path("market/create/product/", views.create_product, name="create_product"),
    path("myProfile/<str:prof_name>/<int:prof_id>/", views.profile, name="profile"),
    path("market/search/", views.search, name="search"),
    path("delete/product/<int:product_id>", views.deleteProduct, name="delete_product"),
    path("market/myproduct/<int:product_id>", views.view_own_product, name="view_own_product"),
    path("<str:user_name>/orders", views.orders, name="orders"),


    # API
    path("update_item/", views.updateItem, name="update_item"),
    path("place_order/", views.placeOrder, name="place_order"),
]

sen301/sen301/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('foodNet/', include('foodNet.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sen301/foodNet/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

class RegisterForm(forms.Form):
    # def validate_username(self, username_to_check):
    #     user = User.query.filter_by(username=username_to_check.data).first()

    #     if user:
    #         raise ValidationError('This Username Already exists! Please try a different username.')


    # def validate_email_address(self, email_address_to_check):
    #     email_address = User.query.filter_by(email=email_address_to_check.data).first()

    #     if email_address:
    #         raise ValidationError(' This Email Address Already exists! Please try a different email address.')
    
    username = forms.CharField(label='Username')
    email_address = forms.EmailField(help_text="A valid email address, please.", label='Email Adress')
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    # password2 = PasswordField(label='Confirm Password', validators=[EqualTo('password1'), DataRequired()])
    
    # title = forms.CharField(label="Title")
    # description = forms.CharField(widget=forms.Textarea, label="Description", required=False)
    # price = forms.IntegerField(label="Initial Price", validators=[MinValueValidator(1)])
    # img_url = forms.URLField(label="Img URL(optional)", required=False)
    
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class':'form-control',
                                                                  'placeholder':'Username', 'required':'True'}))
    password = forms.CharField(label='Password', 
                               widget=forms.PasswordInput(attrs={'class':'form-control',
                                                                  'placeholder':'password', 'required':'True', 
                                                                  'max_length':'80', 'render_value':'False'}))
    
#     def __init__(self, *args, **kwargs):
#         super(BidForm, self).__init__(*args, **kwargs)
#         for visible in self.visible_fields():
#             visible.field.widget.attrs['class'] = 'form-control'

# class AddCommentForm(forms.Form):
#     comment = forms.CharField(widget=forms.Textarea, label="Add a comment")

#     def __init__(self, *args, **kwargs):
#         super(AddCommentForm, self).__init__(*args, **kwargs)
#         for visible in self.visible_fields():
#             visible.field.widget.attrs['class'] = 'form-control'

sen301/foodNet/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import User, Order, OrderItem, Product, Category, ShippingAddress
from .forms import RegisterForm, LoginForm
from django.shortcuts import redirect
from django.contrib import messages
from .templatetags.my_filter import naira
import datetime
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .utils import cookieCart, cartData

# Create your views here.

def home_page(request):
    cookieData = cookieCart(request)
    cartItems = cookieData['cartItems']
    if request.user.is_authenticated:
        return redirect('foodNet:market')
    return render(request, "foodnet/home_page.html", {
        'cartItems': cartItems
    })


def login_view(request):

    # redirect the user to market if he is login
    if request.user.is_authenticated:
        return redirect('foodNet:market')
    
    if request.method == "POST":

        # recuperation of the data first
        form = LoginForm(request.POST)

        if form.is_valid():
            # Attempt to sign user in
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            
            user = authenticate(request, username=username, password=password)

            
            # Check if authentication successful
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("foodNet:market"))
            else:
                    
                messages.info(request, 'Invalid Username/Password! Please Try again.')
                return render(request, "foodnet/login.html", {
                "form": form
            })
                
        else:

            messages.warning(request, 'Please fill the form to login!!')
            return render(request, "foodnet/login.html", {
            "form": form
        })
    else:
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        return render(request, "foodnet/login.html", {
            "form": LoginForm(),
            'cartItems': cartItems,
        })
    

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("foodNet:login"))


def register(request):

    #  redirect the user if he is login
    if request.user.is_authenticated:
        return redirect('foodNet:market')
    
    if request.method == "POST":
        
        first_name = request.POST.get("first_name", False)
        surname = request.POST.get("surname", False)
        middle_name = request.POST.get("middle_name", False)
        username = request.POST["username"]
        email = request.POST.get("email", False)
        
        password = request.POST.get("password", False)
        confirmation = request.POST.get("confirm_password", False)
        
        phone_number = request.POST.get("phone_number", False)
        address1 = request.POST.get("address1", False)
        address2 = request.POST.get("address2", False)        
        state = request.POST.get("state", False)
        city = request.POST.get("city", False)
        zipcode = request.POST.get("zip", False)


        if not(first_name) or not(surname) or not(username) or not(phone_number) or \
            not(address1) or not(city) or not(state):

            messages.warning(request, 'Please fill the form correctly.')
            return render(request, "foodnet/register.html")

        # Ensure password matches confirmation
        if password != confirmation:

            messages.warning(request, 'Passwords must match.')
            return render(request, "foodnet/register.html")

        # Attempt to create new user
        try:
            if not(address2):
                user = User.objects.create_user(first_name=first_name, last_name=surname, middle_name = middle_name, username=username
                                                , email=email, password=password, phone_number=phone_number, address1=address1)
            else:
                user = User.objects.create_user(first_name=first_name, last_name=surname, middle_name = middle_name, username=username
                                                , email=email, password=password, phone_number=phone_number, address1=address1, address2=address2
                                                , state=state, city=city, zipcode=zipcode)

            user.save()
        except IntegrityError:

            messages.info(request, 'Username already taken.')
            return render(request, "foodnet/register.html")
        

        login(request, user)
        messages.success(request, 'Welcome the FoodNet community !! Your account has been created.')
        return HttpResponseRedirect(reverse("foodNet:market"))
    else:
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        return render(request, "foodnet/register.html", {
            "form": RegisterForm(),
            'cartItems': cartItems
        })


def market(request):

    if request.user.is_authenticated:

        client = request.user

        products = Product.objects.all().exclude(vendor=client).order_by('product_timestamp')
        paginator = Paginator(products, 6)
        page_number = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_number)

        
        order, created = Order.objects.get_or_create(client=client,complete=False)
        cartItems = order.get_cart_items

        categories = Category.objects.all()

    else:

       # fetching the cookies
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        
        
        products = Product.objects.all().order_by('product_timestamp')
        paginator = Paginator(products, 6)
        page_number = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_number)
        categories = Category.objects.all()

        if(cookieData['error']):
            messages.info(request, 'Something wrong happen!! Please try again.')
            return render(request, "foodnet/market.html", {
                'products': page_obj,
                'cartItems': cartItems,
                'categories': categories,
                'paginator': paginator
            })

    return render(request, "foodnet/market.html", {
        'products': page_obj,
        'cartItems': cartItems,
        'categories': categories,
        'paginator': paginator 
    })


# @login_required(login_url="/foodNet/login/")
def cart(request):

    data = cartData(request)
    items = data['items']
    order = data['order']
    cartItems = data['cartItems']
    
    if(data['error']):
        messages.info(request, 'Something wrong happen!! Please try again.')
        return render(request, "foodnet/cart.html", {
            'items': items,
            'order': order,
            'cartItems': cartItems,
        })        

    return render(request, "foodnet/cart.html", {
            'items': items,
            'order': order,
            'cartItems': cartItems,
        })


# @login_required(login_url="foodNet/login")
def checkout(request):

    data = cartData(request)
    items = data['items']
    order = data['order']
    cartItems = data['cartItems']
    
    if(data['error']):
        messages.info(request, 'Something wrong happen!! Please try again.')
        return render(request, "foodnet/cart.html", {
            'items': items,
            'order': order,
            'cartItems': cartItems,
        })
    
    return render(request, "foodnet/checkout.html", {
        'items': items,
        'order': order,
        'cartItems': cartItems,
    })


def view_product(request, product_id):

    try:  
        product = Product.objects.get(pk=int(product_id))
    except UnboundLocalError or ValueError:
        messages.info(request, '404 Not Found!! Product not found.')
        return redirect('foodNet:market')
    except Product.DoesNotExist:
        messages.info(request, '404 Not Found!! Product not found.')
        return redirect('foodNet:market')
    
    if request.user.is_authenticated:
        client = request.user
        order, created = Order.objects.get_or_create(client=client, complete=False)
        cartItems = order.get_cart_items
          
    else:
        # fetching the cookies
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        
        if(cookieData['error']):
            messages.info(request, 'Something wrong happen!! Please try again.')
            return render(request, "foodnet/cart.html", {
                'product':product,
                'cartItems': cartItems,
            })

    return render(request, "foodnet/view_product.html",{
        'product':product,
        'cartItems': cartItems
    })


@login_required(login_url="/foodNet/login/")
def create_product(request):
    if request.method == "POST":
        
        name = request.POST.get("name", False)
        description = request.POST.get("description", False)
        price = request.POST.get("price", False)
        category = request.POST.get("category", False)
        image = request.FILES.get("image", False)

        
        if not(name) or not price.isdigit() or not category:
            messages.warning(request, 'Please fill the form correctly.')
            return render(request, "foodnet/create_product.html")
        
        try:
            # if the user provides the image
            if image:
                try:
                    if Category.objects.get(pk=int(category)):

sen301/foodNet/templates/foodnet/cart.html
{% extends 'foodnet/layout.html' %} 
{% load static %}
{% load my_filter %}


{% block title %} Cart {% endblock title %} 

{% block content %}

  
    <!-- messages -->
    </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
                    <strong>{{ message.tags | capfirst }}!</strong> {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    <div>

    <div class="container">

      <div class="row">
        <div class="col-lg-12 p-0">
            
            <table class="table table-dark">
               
                <tr>
                    <th>
                        <a class="btn btn-outline-warning" href="{% url 'foodNet:market' %}">&#x2190; Continue Shopping</a>
                    </th>
                </tr>
                <tr>
                    <th>
                        <h5>Items: <strong>{{ order.get_cart_items }}</strong> </h5>
                    </th>
                    <th>
                        <h5>Total: <strong>{{ order.get_cart_total|naira }}</strong> </h5>
                    </th>
                    <th>
                        <a style="float: right; margin: 5px;" class="btn btn-success" href="{% url 'foodNet:checkout'%}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>
        
        <div class="col-lg-12 p-0">
            <table class="table table-hover table-dark">
                <thead>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Subtotal</th>
                </thead>
            
                <tbody>
                    {% for item in items %}        
                    <tr>
                        <td>
                            <img class="rounded-circle" style="width: 60px; height: 60px;" src="{{ item.product.img.url }}" > {{ item.product.name }}
                        </td>
                        <td>{{ item.product.price|naira }}</td>
                        <td>
                            <div class="d-flex align-items-center">
                                <button data-product="{{ item.product.id }}" data-action="remove" class="btn btn-outline-danger update-cart">-</button>
                                <span class="mx-2"style="text-align: center; font-size: 18px; font-weight: 500;">{{ item.quantity }}</span>
                                <button data-product="{{ item.product.id }}" data-action="add" class="btn btn-outline-success update-cart">+</button>
                            </div>
                        </td>
                        <td>{{ item.get_total|naira }}</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        
      </div>
    </div>

{% endblock content %}

sen301/foodNet/templates/foodnet/home_page.html
{% extends 'foodnet/layout.html' %} 

{% block title %} FoodNet {% endblock title%}

{% block content %}
<div
  class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-dark"
  style="color: white"
>
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">FoodNet Market</h1>
    <p class="lead font-weight-normal">
      Start purchasing products by clicking the link below
    </p>
    <a class="btn btn-primary" href="{% url 'foodNet:market' %}">Get Started</a>
  </div>
  <div class="product-device box-shadow d-none d-md-block"></div>
  <div
    class="product-device product-device-2 box-shadow d-none d-md-block"
  ></div>
</div>
{% endblock content %}

sen301/foodNet/templates/foodnet/layout.html
{% load static %}
{% load my_filter %}

<!DOCTYPE html5>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'foodnet/styles/index.css' %}"/>

    <script type="text/javascript">
      let user = "{{request.user}}";

      // console.log(user)

      function getToken(name){
        let cookieValue = null;
        if (document.cookie && document.cookie !== ''){
          let cookies = document.cookie.split(';');
          
          for(let i = 0; i < cookies.length; i++){
            let cookie = cookies[i].trim();
            // does the cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')){
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      let csrftoken = getToken('csrftoken');


      function getCookie(name){
        // Split cookie string and get all individual name=value pairs in an array
        let cookieArr = document.cookie.split(";");

        // Loop through the array elemets
        for(let i = 0; i < cookieArr.length; i++){
          let cookiePair = cookieArr[i].split("=");

          /* Removing whitespace at the eginning of the cookie name
          and compare it with the given string */
          if(name == cookiePair[0].trim()){
            // Decode the cookie value and return
            return decodeURIComponent(cookiePair[1])
          }
        }

        // Return null if not found
        return null;
      }
      let cart = JSON.parse(getCookie('cart'))
    
      if(cart == undefined){
        cart = {}
        // console.log('cart was created!')
        document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
      }

      // console.log("cart: ", cart)

    </script>

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'foodNet:market' %}">
        <img  style="width: 200px; height: 50px;" src="{% static 'foodnet/assets/foodnet.png' %}" >
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          {% if not user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'foodNet:home_page' %}">
                Home <span class="sr-only">(current)</span>
              </a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'foodNet:market' %}"> Market </a>
          </li>
          {% if user.is_authenticated %}
            <!-- <li class="nav-item">
              <a class="nav-link" href="{% url 'foodNet:orders' user.username %}"> Orders <span class="badge badge-light">9</span> </a>
            </li> -->
          {% endif %}
        </ul>

        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodNet:create_product' %}"> Add Product </a>
            </li>
          
            <li class="nav-item">
              <a class="nav-link" style="color: lawngreen; font-weight: bold">
                {{ user.budget|naira }}
              </a>
            </li>
          {% endif %}
            <li class="nav-item">
              <a class="nav-link" id="cart" href="{% url 'foodNet:cart' %}"> 
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" id="cart-icon" viewBox="0 0 24 24" stroke-width="1.5" height="30" width="30" stroke="rgba(255, 255, 255, .5)">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                </svg> <span class="badge badge-light">{{ cartItems }}</span>
              </a>
            </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" id="profile" href="{% url 'foodNet:profile' prof_name=user.username prof_id=user.id %}"> 
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" height="30" width="30" stroke="rgba(255, 255, 255, .5)">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                </svg>
                
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link"> Welcome, {{ user.first_name.title }} </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodNet:logout' %}"> Logout </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodNet:login' %}"> Login </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodNet:register' %}"> Register </a>
            </li>
          {% endif %}
        </ul>
       
      </div>
    </nav>

    <!-- flash messages -->

    {% block content %}
    {% endblock %}
    
    {% block script %}
    <script src="{% static 'foodnet/js/cart.js' %}"></script>
    {% endblock %}

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
   
  </body>
</html>

sen301/foodNet/templates/foodnet/login.html
{% extends 'foodnet/layout.html' %} 

{% load static %}

{% block title %} Login {% endblock title %} 

{% block content %}
<body class="text-center">

  </div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
                <strong>{{ message.tags | capfirst }}!</strong> {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
  <div>

  <div class="container mt-4">
    <form method="POST" action="{% url 'foodNet:login' %}" class="form-signin" style="color: white">
      <!-- againt a cross site Request Forgery (CSRF) -->
      {% csrf_token %}

      <img style="width: 680px; height: 200px;" src="{% static 'foodnet/assets/foodnet.png' %}" >
      <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>
      
      <br />
            {% for field in form %}
                <div class="form-group">

                    {{ field.label_tag}}
                    <br>
                    {{ field }}

                </div>
            {% endfor %}
      <br />

      <div class="checkbox mb-3">
        <h6>Do not have an account?</h6>
        <a
          class="btn btn-sm btn-secondary"
          href="{% url 'foodNet:register' %}"
          >Register</a
        >
      </div>

      <input type="submit" class='btn btn-lg btn-block btn-primary' value="Log In">
    </form>
  </div>
</body>
{% endblock content %}

sen301/foodNet/templates/foodnet/market.html
{% extends 'foodnet/layout.html' %} 
{% load static %}
{% load my_filter %}

{% block title %} Market {% endblock title %} 

{% block content %}

    <!-- messages -->
    </div>
      {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
                  <strong>{{ message.tags | capfirst }}!</strong> {{message}}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
          {% endfor %}
      {% endif %}
    <div>
      

    <div class="container mt-2 d-flex justify-content-between">
      <div>
        <h2>Available Products on the Market</h2>
        <p>Click on one of the items to start buying</p>
      </div>
      <div>
        <form class="form-inline" action="{% url 'foodNet:search' %}" method="GET">
          {% csrf_token %}
          <div class="form-group">
              <label for="category">Search by Category: </label>
              <select id="category" name="category" class="form-control ml-lg-2 mr-lg-2">
                  <option selected value="all">All</option>
                  {% for category in categories %}
                  <option value="{{ category.id }}">{{ category }}</option>
                  {% endfor %}
              </select>
          </div>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
      
      <br />
      
    </div>
    <div class="container">

      <div class="row row-cols-3">
        <!-- products -->
        {% for product in products.object_list %}

          <div class="col mb-2" id="cart">
            <div style="margin-bottom: 5px" class="card text-center bg-dark">
              <div class="card-body">
                <img class="rounded-lg" style="width: 250px; height: 130px; object-fit: cover;" src="{{ product.img.url }}" >
                
                  <h5 class="card-title mx-auto mt-2 pb-1 d-block text-truncate" style="max-width: 200px;">{{ product.name.title }}</h5>

                  <h5 class="card-title mx-auto d-block text-truncate">{{ product.price |naira }}</h5>
                  <div class="product">
                    
                    <hr>
                    <div class="d-flex justify-content-between align-items-center">

                      <div class="d-flex justify-content-between">
                        <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-warning update-cart">
                          Add cart <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" height="30" width="30" stroke="black">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                          </svg>
                        </button>
                        <a class="btn btn-outline-success ml-2" href="{% url 'foodNet:view_product' product.id %}">View</a>
                      </div>

                      <!-- <h4 class="d-block text-truncate" style="display: incline-block; float: right; max-width: 100px;">{{ product.price |naira }}</h4> -->

                    </div>
                    
                  </div>
                
              </div>
            </div>
          </div>

        {% empty %}
        <div>
          <h1 style="color: white; font-weight: bold">No Product you can buy in Market</h1>
        </div>
        {% endfor %}
        
      </div>

      
        {% for num in paginator.page_range %}
          {% if products.number == num %}
            
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>

          {% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
            
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          
          {% endif %}
        {% endfor %}
      
    </div>

    <script type="text/javascript">
      var loginUrl = "{% url 'foodNet:login' %}";
      
  </script>

{% endblock content %}